### ISSUE TITLE
add the total amount of votes for the maps in the /rankings command

### ISSUE THREAD

**Issue by Mr-Pengu** [davidbmaier/todt-bot#7]
Being able to see how many people voted for it to be in that posotion would add slightly more merit to its quality or lack there of.

**Comment by davidbmaier** [comment]
For reference when I look into this: This will need some data structure changes to associate the ratings numbers with the rankings - might be worth adding that to the ranking data directly.

**Comment by davidbmaier** [comment]
Added this in 457dac45609ec99bc06005fbfcfb696d49c803ad along with some general improvements to the rankings command. Let me know if something breaks, didn't have a lot of time for extended testing.
